"""Added address field to students

Revision ID: 76dee6fde483
Revises: 8d2afcd2ec32
Create Date: 2026-05-15 18:26:12.374414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# This migration runs after the initial migration.
revision: str = '76dee6fde483'
down_revision: Union[str, Sequence[str], None] = '8d2afcd2ec32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the optional address column to existing student records.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Remove the address column if this migration is rolled back.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'address')
    # ### end Alembic commands ###
