"""Initial migration

Revision ID: 8d2afcd2ec32
Revises: 
Create Date: 2026-05-15 18:10:31.826239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# This is the first migration, so it has no down_revision.
revision: str = '8d2afcd2ec32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Initial migration currently has no generated table operations.
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Nothing to undo because the upgrade does not create objects.
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
